"""add invoice due_date

Revision ID: 1082c708d22a
Revises: 9b4198f9996e
Create Date: 2026-10-09 18:23:16.844824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1082c708d22a'
down_revision: Union[str, Sequence[str], None] = '9b4198f9996e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_column('invoices', 'due_date')
    # ### end Alembic commands ###
