"""add user.has_notification and Accepted invoice status

Revision ID: 164feda5784f
Revises: c0ec220b9cfd
Create Date: 2026-09-19 16:59:32.707168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164feda5784f'
down_revision: Union[str, Sequence[str], None] = 'c0ec220b9cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('has_notification', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Autogenerate doesn't diff Postgres native enum VALUES (only whole
    # columns/types) — added by hand. Safe inside this transaction on
    # Postgres 12+ as long as the new value isn't used in the same
    # transaction, which it isn't here.
    op.execute("ALTER TYPE invoice_status_enum ADD VALUE 'Accepted'")


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no ALTER TYPE ... DROP VALUE. Standard workaround:
    # refuse if any row actually uses 'Accepted' (nothing sane to migrate
    # it to), then rebuild the enum type without that value.
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM invoices WHERE invoice_status = 'Accepted') THEN
                RAISE EXCEPTION 'Cannot downgrade: invoices with status ''Accepted'' exist';
            END IF;
        END $$;
    """)
    op.execute("ALTER TYPE invoice_status_enum RENAME TO invoice_status_enum_old")
    op.execute("CREATE TYPE invoice_status_enum AS ENUM ('Generated', 'Assigned', 'Pending', 'Paid', 'Declined')")
    op.execute(
        "ALTER TABLE invoices ALTER COLUMN invoice_status "
        "TYPE invoice_status_enum USING invoice_status::text::invoice_status_enum"
    )
    op.execute("DROP TYPE invoice_status_enum_old")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'has_notification')
    # ### end Alembic commands ###
