"""add notifications table, user.created_by, drop has_notification

Revision ID: 1cfdedc97efd
Revises: f9c2faedaeb0
Create Date: 2026-09-20 15:13:48.756417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfdedc97efd'
down_revision: Union[str, Sequence[str], None] = 'f9c2faedaeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('related_invoice_id', sa.UUID(), nullable=True),
    sa.Column('related_user_id', sa.UUID(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_user_id'], ['user_data.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_data', sa.Column('created_by', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'user_data', 'user_data', ['created_by'], ['user_id'])
    op.drop_column('user_data', 'has_notification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('has_notification', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    # Constraint name filled in by hand — confirmed against the real DB
    # after applying upgrade(), same as the earlier final_invoice_id migration.
    op.drop_constraint('user_data_created_by_fkey', 'user_data', type_='foreignkey')
    op.drop_column('user_data', 'created_by')
    op.drop_table('notifications')
    # ### end Alembic commands ###
