"""add api_logs

Revision ID: 3cd70a86ce12
Revises: b1717c5e72f7
Create Date: 2026-10-02 17:54:40.756460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cd70a86ce12'
down_revision: Union[str, Sequence[str], None] = 'b1717c5e72f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('query_params', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.org_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('api_logs_occurred_at', 'api_logs', ['occurred_at'], unique=False)
    op.create_index('api_logs_org_occurred_at', 'api_logs', ['org_id', 'occurred_at'], unique=False)
    op.create_index('api_logs_user_occurred_at', 'api_logs', ['user_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('api_logs_user_occurred_at', table_name='api_logs')
    op.drop_index('api_logs_org_occurred_at', table_name='api_logs')
    op.drop_index('api_logs_occurred_at', table_name='api_logs')
    op.drop_table('api_logs')
    # ### end Alembic commands ###
