"""add menu_item_embeddings table

Revision ID: 4821e0dd3b67
Revises: e0e2badceeaf
Create Date: 2026-09-18 12:17:46.670731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
# ^ autogenerate referenced pgvector.sqlalchemy.vector.VECTOR below without
# importing it at all — a known gap with custom column types and
# autogenerate. Fixed by importing the same Vector class used in
# embeddings/model.py and referencing that instead of the unqualified,
# unimported dotted path.


# revision identifiers, used by Alembic.
revision: str = '4821e0dd3b67'
down_revision: Union[str, Sequence[str], None] = 'e0e2badceeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_item_embeddings',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('embedded_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_embeddings')
    # ### end Alembic commands ###
