"""add billing history and billing info tables, invoice subproject link

Revision ID: 53192ce76860
Revises: 8448a1c35490
Create Date: 2026-09-26 16:59:15.957960

billing_history is the append-only transaction log (one row per payment,
refund, decline, ...); billing_info is a one-row-per-subproject running
summary. invoices.subproject_id (nullable) is what makes "billing history
for this subproject" a well-defined query — a project can have several
subprojects, so knowing the project alone isn't enough.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53192ce76860'
down_revision: Union[str, Sequence[str], None] = '8448a1c35490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_info',
    sa.Column('subproject_id', sa.UUID(), nullable=False),
    sa.Column('total_invoiced', sa.Float(), nullable=True),
    sa.Column('total_paid', sa.Float(), nullable=True),
    sa.Column('total_refunded', sa.Float(), nullable=True),
    sa.Column('balance_due', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('payment_pending', 'partial_payment_received', 'paid_in_full', 'overdue', name='billing_status_enum'), nullable=False),
    sa.Column('last_event_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.subproject_id'], ),
    sa.PrimaryKeyConstraint('subproject_id')
    )
    op.create_table('billing_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.Enum('Manual', 'Stripe', name='source_enum'), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('invoices', sa.Column('subproject_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'subprojects', ['subproject_id'], ['subproject_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_subproject_id_fkey', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'subproject_id')
    op.drop_table('billing_history')
    op.drop_table('billing_info')
    # ### end Alembic commands ###

    # Postgres enum TYPEs aren't dropped automatically when the table using
    # them is dropped (a type can be shared by more than one column/table,
    # so Alembic never assumes it's safe to). Without this, re-running
    # upgrade() after a downgrade fails with "type already exists".
    op.execute('DROP TYPE billing_status_enum')
    op.execute('DROP TYPE source_enum')
