"""add billing_info next_due_date

Revision ID: 605a613b6bcb
Revises: 1082c708d22a
Create Date: 2026-10-09 18:58:55.912289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605a613b6bcb'
down_revision: Union[str, Sequence[str], None] = '1082c708d22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_info', sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_info', 'next_due_date')
    # ### end Alembic commands ###
