"""link invoices to projects, drop unused project_invoice

Revision ID: 7813e513f05a
Revises: fea857b211c9
Create Date: 2026-09-19 14:03:11.149729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7813e513f05a'
down_revision: Union[str, Sequence[str], None] = 'fea857b211c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('project_associated_to', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'invoices', 'projects', ['project_associated_to'], ['project_id'])
    op.drop_constraint(op.f('projects_projectInvoice_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'projectInvoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('projectInvoice', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_projectInvoice_fkey'), 'projects', 'invoices', ['projectInvoice'], ['invoice_id'])
    # Constraint name filled in by hand — autogenerate can't know the name
    # Postgres assigns to a create_foreign_key(None, ...) call ahead of
    # time; confirmed against the real DB after applying upgrade().
    op.drop_constraint('invoices_project_associated_to_fkey', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'project_associated_to')
    # ### end Alembic commands ###
