"""add hnsw index on menu_item_embeddings

Revision ID: 82f0c7161eb4
Revises: 4821e0dd3b67
Create Date: 2026-09-18 12:49:57.101765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f0c7161eb4'
down_revision: Union[str, Sequence[str], None] = '4821e0dd3b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('menu_item_embeddings_hnsw_cosine', 'menu_item_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('menu_item_embeddings_hnsw_cosine', table_name='menu_item_embeddings', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###
