"""explicit delete rules on foreign keys

Revision ID: 87bba32a3858
Revises: 622c3537d0c7
Create Date: 2026-10-05 17:46:11.922893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bba32a3858'
down_revision: Union[str, Sequence[str], None] = '622c3537d0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('account_activity_project_id_fkey'), 'account_activity', type_='foreignkey')
    op.drop_constraint(op.f('account_activity_subproject_id_fkey'), 'account_activity', type_='foreignkey')
    op.drop_constraint(op.f('account_activity_actor_id_fkey'), 'account_activity', type_='foreignkey')
    op.create_foreign_key(op.f('account_activity_project_id_fkey'), 'account_activity', 'projects', ['project_id'], ['project_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('account_activity_actor_id_fkey'), 'account_activity', 'user_data', ['actor_id'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('account_activity_subproject_id_fkey'), 'account_activity', 'subprojects', ['subproject_id'], ['subproject_id'], ondelete='SET NULL')
    op.drop_constraint(op.f('billing_history_invoice_id_fkey'), 'billing_history', type_='foreignkey')
    op.create_foreign_key(op.f('billing_history_invoice_id_fkey'), 'billing_history', 'invoices', ['invoice_id'], ['invoice_id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('billing_info_subproject_id_fkey'), 'billing_info', type_='foreignkey')
    op.create_foreign_key(op.f('billing_info_subproject_id_fkey'), 'billing_info', 'subprojects', ['subproject_id'], ['subproject_id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('invoices_subproject_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_invoice_assigned_to_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_project_associated_to_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_invoice_assigned_to_fkey'), 'invoices', 'user_data', ['invoice_assigned_to'], ['user_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('invoices_project_associated_to_fkey'), 'invoices', 'projects', ['project_associated_to'], ['project_id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('invoices_subproject_id_fkey'), 'invoices', 'subprojects', ['subproject_id'], ['subproject_id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('menu_item_embeddings_item_id_fkey'), 'menu_item_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('menu_item_embeddings_item_id_fkey'), 'menu_item_embeddings', 'menu_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_organization_id_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('fk_projects_final_invoice_id'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_vendor_on_project_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_organization_id_fkey'), 'projects', 'organizations', ['organization_id'], ['org_id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_projects_final_invoice_id', 'projects', 'invoices', ['final_invoice_id'], ['invoice_id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('projects_vendor_on_project_fkey'), 'projects', 'user_data', ['vendor_on_project'], ['user_id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('subprojects_project_associated_to_fkey'), 'subprojects', type_='foreignkey')
    op.create_foreign_key(op.f('subprojects_project_associated_to_fkey'), 'subprojects', 'projects', ['project_associated_to'], ['project_id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('user_data_created_by_fkey'), 'user_data', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_data_user_org'), 'user_data', type_='foreignkey')
    op.create_foreign_key(op.f('user_data_created_by_fkey'), 'user_data', 'user_data', ['created_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key('fk_user_data_user_org', 'user_data', 'organizations', ['user_org'], ['org_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_data_user_org', 'user_data', type_='foreignkey')
    op.drop_constraint(op.f('user_data_created_by_fkey'), 'user_data', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_data_user_org'), 'user_data', 'organizations', ['user_org'], ['org_id'])
    op.create_foreign_key(op.f('user_data_created_by_fkey'), 'user_data', 'user_data', ['created_by'], ['user_id'])
    op.drop_constraint(op.f('subprojects_project_associated_to_fkey'), 'subprojects', type_='foreignkey')
    op.create_foreign_key(op.f('subprojects_project_associated_to_fkey'), 'subprojects', 'projects', ['project_associated_to'], ['project_id'])
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_constraint(op.f('projects_vendor_on_project_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint('fk_projects_final_invoice_id', 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_organization_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_vendor_on_project_fkey'), 'projects', 'user_data', ['vendor_on_project'], ['user_id'])
    op.create_foreign_key(op.f('fk_projects_final_invoice_id'), 'projects', 'invoices', ['final_invoice_id'], ['invoice_id'])
    op.create_foreign_key(op.f('projects_organization_id_fkey'), 'projects', 'organizations', ['organization_id'], ['org_id'])
    op.drop_constraint(op.f('menu_item_embeddings_item_id_fkey'), 'menu_item_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('menu_item_embeddings_item_id_fkey'), 'menu_item_embeddings', 'menu_items', ['item_id'], ['id'])
    op.drop_constraint(op.f('invoices_subproject_id_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_project_associated_to_fkey'), 'invoices', type_='foreignkey')
    op.drop_constraint(op.f('invoices_invoice_assigned_to_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_project_associated_to_fkey'), 'invoices', 'projects', ['project_associated_to'], ['project_id'])
    op.create_foreign_key(op.f('invoices_invoice_assigned_to_fkey'), 'invoices', 'user_data', ['invoice_assigned_to'], ['user_id'])
    op.create_foreign_key(op.f('invoices_subproject_id_fkey'), 'invoices', 'subprojects', ['subproject_id'], ['subproject_id'])
    op.drop_constraint(op.f('billing_info_subproject_id_fkey'), 'billing_info', type_='foreignkey')
    op.create_foreign_key(op.f('billing_info_subproject_id_fkey'), 'billing_info', 'subprojects', ['subproject_id'], ['subproject_id'])
    op.drop_constraint(op.f('billing_history_invoice_id_fkey'), 'billing_history', type_='foreignkey')
    op.create_foreign_key(op.f('billing_history_invoice_id_fkey'), 'billing_history', 'invoices', ['invoice_id'], ['invoice_id'])
    op.drop_constraint(op.f('account_activity_subproject_id_fkey'), 'account_activity', type_='foreignkey')
    op.drop_constraint(op.f('account_activity_actor_id_fkey'), 'account_activity', type_='foreignkey')
    op.drop_constraint(op.f('account_activity_project_id_fkey'), 'account_activity', type_='foreignkey')
    op.create_foreign_key(op.f('account_activity_actor_id_fkey'), 'account_activity', 'user_data', ['actor_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('account_activity_subproject_id_fkey'), 'account_activity', 'subprojects', ['subproject_id'], ['subproject_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('account_activity_project_id_fkey'), 'account_activity', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
