"""use native uuid for live stations and price tiers

Revision ID: 9858e3197678
Revises: 6130c6ea72ee
Create Date: 2026-10-05 14:05:44.702831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9858e3197678"
down_revision: Union[str, Sequence[str], None] = "6130c6ea72ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "live_stations",
        "id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        postgresql_using="id::uuid",
        existing_nullable=False,
    )
    op.alter_column(
        "price_tiers",
        "id",
        existing_type=sa.VARCHAR(),
        type_=sa.UUID(),
        postgresql_using="id::uuid",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "price_tiers",
        "id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        postgresql_using="id::text",
        existing_nullable=False,
    )
    op.alter_column(
        "live_stations",
        "id",
        existing_type=sa.UUID(),
        type_=sa.VARCHAR(),
        postgresql_using="id::text",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
