"""added soft delete for invoice

Revision ID: 9b4198f9996e
Revises: 87bba32a3858
Create Date: 2026-10-05 20:35:01.200960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4198f9996e'
down_revision: Union[str, Sequence[str], None] = '87bba32a3858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_history', sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('billing_history', sa.Column('voided_reason', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_data', sa.Column('user_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'user_disabled')
    op.drop_column('invoices', 'invoice_deleted_at')
    op.drop_column('billing_history', 'voided_reason')
    op.drop_column('billing_history', 'voided_at')
    # ### end Alembic commands ###
