"""add account activity table

Revision ID: b336bf1a0359
Revises: 8448a1c35490
Create Date: 2026-09-26 19:16:28.078031

The project-lifecycle activity log behind the activity stepper (project
created, subproject created, ...). project_id is nullable specifically
for "user created" events, which have no project yet. Every FK cascades
on delete — an activity row is ephemeral/derived, never something that
should block deleting the project/subproject/user it references. Payment
events are deliberately NOT logged here — billing_history stays the
single source of truth for those, merged in at read time.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b336bf1a0359'
down_revision: Union[str, Sequence[str], None] = '8448a1c35490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('subproject_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['user_data.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subproject_id'], ['subprojects.subproject_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_activity')
    # ### end Alembic commands ###
