"""add project.final_invoice_id

Revision ID: c0ec220b9cfd
Revises: 7813e513f05a
Create Date: 2026-09-19 14:32:36.510845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ec220b9cfd'
down_revision: Union[str, Sequence[str], None] = '7813e513f05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('final_invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_projects_final_invoice_id', 'projects', 'invoices', ['final_invoice_id'], ['invoice_id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_projects_final_invoice_id', 'projects', type_='foreignkey')
    op.drop_column('projects', 'final_invoice_id')
    # ### end Alembic commands ###
