"""add foreign key indexes

Revision ID: cb604f81d85c
Revises: f9739eda0b0a
Create Date: 2026-10-04 18:50:19.090065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb604f81d85c'
down_revision: Union[str, Sequence[str], None] = 'f9739eda0b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_activity_actor_id'), 'account_activity', ['actor_id'], unique=False)
    op.create_index(op.f('ix_account_activity_project_id'), 'account_activity', ['project_id'], unique=False)
    op.create_index(op.f('ix_account_activity_subproject_id'), 'account_activity', ['subproject_id'], unique=False)
    op.create_index(op.f('ix_billing_history_invoice_id'), 'billing_history', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_assigned_to'), 'invoices', ['invoice_assigned_to'], unique=False)
    op.create_index(op.f('ix_invoices_project_associated_to'), 'invoices', ['project_associated_to'], unique=False)
    op.create_index(op.f('ix_invoices_subproject_id'), 'invoices', ['subproject_id'], unique=False)
    op.create_index(op.f('ix_item_relationships_from_item_id'), 'item_relationships', ['from_item_id'], unique=False)
    op.create_index(op.f('ix_item_relationships_to_item_id'), 'item_relationships', ['to_item_id'], unique=False)
    op.create_index(op.f('ix_menu_items_tax_category_id'), 'menu_items', ['tax_category_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_invoice_id'), 'notifications', ['related_invoice_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_user_id'), 'notifications', ['related_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('notifications_unread_by_user', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_index(op.f('ix_projects_final_invoice_id'), 'projects', ['final_invoice_id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_vendor_on_project'), 'projects', ['vendor_on_project'], unique=False)
    op.create_index(op.f('ix_subprojects_project_associated_to'), 'subprojects', ['project_associated_to'], unique=False)
    op.create_index(op.f('ix_user_data_user_org'), 'user_data', ['user_org'], unique=False)
    op.create_index('user_projects_project_id', 'user_projects', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_projects_project_id', table_name='user_projects')
    op.drop_index(op.f('ix_user_data_user_org'), table_name='user_data')
    op.drop_index(op.f('ix_subprojects_project_associated_to'), table_name='subprojects')
    op.drop_index(op.f('ix_projects_vendor_on_project'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_final_invoice_id'), table_name='projects')
    op.drop_index('notifications_unread_by_user', table_name='notifications', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_invoice_id'), table_name='notifications')
    op.drop_index(op.f('ix_menu_items_tax_category_id'), table_name='menu_items')
    op.drop_index(op.f('ix_item_relationships_to_item_id'), table_name='item_relationships')
    op.drop_index(op.f('ix_item_relationships_from_item_id'), table_name='item_relationships')
    op.drop_index(op.f('ix_invoices_subproject_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_project_associated_to'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_assigned_to'), table_name='invoices')
    op.drop_index(op.f('ix_billing_history_invoice_id'), table_name='billing_history')
    op.drop_index(op.f('ix_account_activity_subproject_id'), table_name='account_activity')
    op.drop_index(op.f('ix_account_activity_project_id'), table_name='account_activity')
    op.drop_index(op.f('ix_account_activity_actor_id'), table_name='account_activity')
    # ### end Alembic commands ###
