"""add organizations table and org scoping

Revision ID: cb678f59a679
Revises: 8448a1c35490
Create Date: 2026-09-27 20:41:52.610430

Adds the Organization tenant root plus the two scoping columns this app
directly owns: projects.organization_id (the single source of truth for
which tenant a piece of business data belongs to — invoices/subprojects
scope by joining through their project rather than each carrying their
own copy) and user_data.user_org (nullable; only meaningful for vendor
rows — a client relates to an org through whichever projects they're
linked to, not a standing membership).

Real data migration, not just schema: this app currently has exactly one
real business's data, and nothing before this migration has ever had an
organization to belong to. A default Organization is created and every
existing project/vendor is backfilled to point at it, so nothing goes
silently org-less the moment this lands.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb678f59a679'
down_revision: Union[str, Sequence[str], None] = '8448a1c35490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('org_name', sa.String(), nullable=False),
    sa.Column('org_vendor', sa.UUID(), nullable=True),
    sa.Column('org_created_at', sa.DateTime(), nullable=True),
    sa.Column('org_email', sa.String(), nullable=False),
    sa.Column('org_disabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_vendor'], ['user_data.user_id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.add_column('projects', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_projects_organization_id', 'projects', 'organizations', ['organization_id'], ['org_id'])
    op.add_column('user_data', sa.Column('user_org', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_user_data_user_org', 'user_data', 'organizations', ['user_org'], ['org_id'], use_alter=True)
    # ### end Alembic commands ###

    # Seed a default org from whichever vendor already exists (if any —
    # a brand-new/test database has none yet, which is fine, org_vendor
    # is nullable), then backfill every existing project and vendor to it.
    op.execute("""
        DO $$
        DECLARE
            default_org_id UUID;
            first_vendor_id UUID;
            first_vendor_email VARCHAR;
        BEGIN
            SELECT user_id, email INTO first_vendor_id, first_vendor_email
            FROM user_data WHERE role = 'vendor' ORDER BY created_at LIMIT 1;

            INSERT INTO organizations (org_id, org_name, org_vendor, org_email, org_disabled, org_created_at)
            VALUES (
                gen_random_uuid(),
                'Default Organization',
                first_vendor_id,
                COALESCE(first_vendor_email, 'vendor@example.com'),
                false,
                now()
            )
            RETURNING org_id INTO default_org_id;

            UPDATE projects SET organization_id = default_org_id WHERE organization_id IS NULL;
            UPDATE user_data SET user_org = default_org_id WHERE role = 'vendor' AND user_org IS NULL;
        END $$;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_data_user_org', 'user_data', type_='foreignkey')
    op.drop_column('user_data', 'user_org')
    op.drop_constraint('fk_projects_organization_id', 'projects', type_='foreignkey')
    op.drop_column('projects', 'organization_id')
    op.drop_table('organizations')
    # ### end Alembic commands ###
