"""add invoice total and deposit percentage

Revision ID: cc9ac029a91e
Revises: 3cd70a86ce12
Create Date: 2026-10-02 20:41:57.899654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9ac029a91e'
down_revision: Union[str, Sequence[str], None] = '3cd70a86ce12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('deposit_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'deposit_percentage')
    op.drop_column('invoices', 'total_amount')
    # ### end Alembic commands ###
