"""baseline existing schema

Revision ID: e0e2badceeaf
Revises:
Create Date: 2026-09-13 14:20:45.732528

NOTE: hand-edited after autogenerate. The raw autogenerated diff also wanted
to drop all 14 Prisma-managed tables (menu_items, events, users, etc.) —
those belong to madras-menu-studio's own Prisma schema, not to this repo's
SQLAlchemy models, and this migration must never touch them. Only the real
diff against tables this app owns (adding services' missing columns) is
kept below.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0e2badceeaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('services', sa.Column('religion', sa.Enum('Hindu', 'Muslim', 'Christian', name='religion_enum'), nullable=True))
    op.add_column('services', sa.Column('service_date', sa.DateTime(), nullable=False))
    op.add_column('services', sa.Column('guest_count', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('service_type', sa.Enum('Buffet', 'Plated', 'Family Style', 'Live Stations', 'Butler Passed', name='service_type_enum'), nullable=False))
    op.add_column('services', sa.Column('venue', sa.Enum('Hotel', 'Country Club', 'Mueseum', 'Party Hall', 'Home', 'Outdoor', name='venue_enum'), nullable=False))
    op.add_column('services', sa.Column('service_event', sa.Enum('breakfast', 'wedding Lunch', 'Wedding Dinner', 'Anniversary', 'birthday', 'cockatail hour', 'mehendi', 'haldi', 'ceremony refreshments', 'vidai', 'welcome dinner', 'welcome lunch', 'baarat', 'Walima', 'Graduation', 'house Warming', 'High tea', name='event_enum'), nullable=False))
    op.add_column('services', sa.Column('min_price_per_person', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('max_price_per_person', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('services', 'max_price_per_person')
    op.drop_column('services', 'min_price_per_person')
    op.drop_column('services', 'service_event')
    op.drop_column('services', 'venue')
    op.drop_column('services', 'service_type')
    op.drop_column('services', 'guest_count')
    op.drop_column('services', 'service_date')
    op.drop_column('services', 'religion')
