"""add permissions and role_permissions tables

Revision ID: f9c2faedaeb0
Revises: 164feda5784f
Create Date: 2026-09-20 12:57:53.690836

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# alembic/env.py already puts the project root on sys.path before any
# migration module is imported, so this resolves the same way models/auth
# imports do everywhere else in this app.
from auth.permissions import PERMISSIONS


# revision identifiers, used by Alembic.
revision: str = 'f9c2faedaeb0'
down_revision: Union[str, Sequence[str], None] = '164feda5784f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


permissions_table = sa.table(
    "permissions",
    sa.column("id", sa.UUID),
    sa.column("name", sa.String),
    sa.column("description", sa.String),
)
role_permissions_table = sa.table(
    "role_permissions",
    sa.column("role", sa.String),
    sa.column("permission_id", sa.UUID),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.PrimaryKeyConstraint('role', 'permission_id')
    )
    # ### end Alembic commands ###

    # Seed: every permission above, all granted to "vendor".
    # "client" gets none — their access is entirely identity/resource-scoped
    # (user_projects, invoiceAssignedTo), not permission-table-driven. A
    # future "staff"/"chef" role gets its own row here later, no code change.
    permission_rows = [{"id": uuid.uuid4(), "name": name, "description": desc} for name, desc in PERMISSIONS]
    op.bulk_insert(permissions_table, permission_rows)
    op.bulk_insert(
        role_permissions_table,
        [{"role": "vendor", "permission_id": row["id"]} for row in permission_rows],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
