"""add password_hash to user_data

Revision ID: fea857b211c9
Revises: 82f0c7161eb4
Create Date: 2026-09-18 17:29:25.010884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea857b211c9'
down_revision: Union[str, Sequence[str], None] = '82f0c7161eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'password_hash')
    # ### end Alembic commands ###
